targets:
  $default:
    builders:
      mockito|mockBuilder:
        enabled: true
        generate_for:
          include:
            - test/mocks.dart
      hive_generator:
        enabled: true
        generate_for:
          include:
            - lib/services/*/models/*.dart
